## Install extension vscode : REST Client Huachao Mao

## REMEMBER: This comment ### divides the request

#### GET ALL USERS ####
GET http://localhost:3000/user

#### CREATE ####
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
	"name"   : "gilberto",
	"email"  : "gilberto@gmail.com",
	"password": "12345",
	"birth_at": "1969-08-29T21:29:51.651Z"
}
#### SEARCH BY ID ####
GET http://localhost:3000/user/14

#### DELETE BY ID ####
DELETE http://localhost:3000/user/14

#### UPDATE WITH PUT ####
PUT http://localhost:3000/user/14 HTTP/1.1
content-type: application/json

{
	"name"   : "yyy",
	"email"  : "dsdfsdfasd@gmail.com",
	"password": "12345",
	"birth_at": "1969-08-29T21:29:51.651Z"
}

#### UPDATE WITH PATCH - PARTIAL  ####
PUT http://localhost:3000/user/11 HTTP/1.1
content-type: application/json

{
	"name"   : "yyy",
	"email"  : "dsdfsdfasd@gmail.com",
	"password": "12345",
	"birth_at": "1969-08-29T21:29:51.651Z"
}
